# Generated by Django 5.2 on 2025-06-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='core.servicecategory'),
            preserve_default=False,
        ),
    ]
